# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='roomId',
            new_name='chatroom',
        ),
    ]
