# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wingmanreview',
            unique_together=set([('userReviewed', 'userReviewer')]),
        ),
    ]
