# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171021_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wingmanreview',
            old_name='userReviewed',
            new_name='reviewee',
        ),
        migrations.RenameField(
            model_name='wingmanreview',
            old_name='userReviewer',
            new_name='reviewer',
        ),
        migrations.AlterUniqueTogether(
            name='wingmanreview',
            unique_together=set([('reviewee', 'reviewer')]),
        ),
    ]
