# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171021_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wingmanreview',
            old_name='value',
            new_name='rating',
        ),
    ]
