# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171021_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='wingmanuser',
            name='isSuper',
            field=models.BooleanField(default=False),
        ),
    ]
