# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_wingmanuser_issuper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wingmanuser',
            old_name='isSuper',
            new_name='isPremium',
        ),
    ]
