# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20171025_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='wingmanuser',
            name='averageRating',
            field=models.IntegerField(default=0),
        ),
    ]
